const DATA = {
  // multiple and binary questions
  "בהד-6": {
    "קורס-1": {
      tools: {
        amountOfQuestions: 3,
        tool0: {
          name: "פטיש",
          explanation:
            "הפטיש הוא חלק ממשפחת הכלים לשימוש יומיומי. הפטיש מאפשר לתלות מדפים ומסייע בתיקון תקלות בתשתיות ומבנים.",
          questions: [
            {
              type: `multiple`,
              question: ` שאלה שאלתית בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
            {
              type: `multiple`,
              question: `איך קוראים לי?`,
              ans1: `שיר`,
              ans2: `נגה`,
              ans3: `תמר`,
              ans4: `אלון`,
              correctAns: `ans3`,
            },
            {
              type: `multiple`,
              question: `בת כמה אני?`,
              ans1: `16`,
              ans2: `19`,
              ans3: `22`,
              ans4: `80`,
              correctAns: `ans2`,
            },
          ],
        },
        tool1: {
          name: "מפתח ברגים",
          explanation:
            "מפתח הברגים הוא חלק ממשפחת הכלים הביתיים. הוא מאפשר להדק ולפתוח סוגי ברגים שונים וגם כדי להחזיק דיבלים.",
          questions: [
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `טעות`,
              ans2: `טעות`,
              ans3: `נכון`,
              ans4: `טעות`,
              correctAns: `ans3`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `טעות`,
              ans2: `נכון`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans2`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `טעות`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `נכון`,
              correctAns: `ans4`,
            },
          ],
        },
        tool2: {
          name: "מסור",
          explanation:
            "המסור הוא חלק ממשפחת הכלים לשימוש מקצועי בלבד. המסור מאפשר לבצע חיתוכים גדולים בחומרים קשיחים.",
          questions: [
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `טעות`,
              ans2: `טעות`,
              ans3: `נכון`,
              ans4: `טעות`,
              correctAns: `ans3`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `טעות`,
              ans2: `נכון`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans2`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
          ],
        },
        tool3: {
          name: "מברג",
          explanation:
            "המברג הוא חלק ממשפחת הכלים לפירוק פצצות ויכול לשמש לפתיחת מארז הפצצה.",
          questions: [
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
          ],
        },
        tool4: {
          name: "פלייר",
          explanation:
            "הפלייר נחשב חלק ממשפחת הכלים לפירוק פצצות ויכול לשמש לשליפת מסמרים שתקועים במארז הפצצה או לתפיסה מדויקת של חוטי חשמל.",
          questions: [
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
          ],
        },
        tool5: {
          name: "סרט מידה",
          explanation:
            "סרט המידה הוא חלק ממשפחת הכלים לשימוש יומיומי והוא משמש למדידת גדלים של רהיטים או מידות של בגדים.",
          questions: [
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `טעות`,
              ans2: `נכון`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans2`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
          ],
        },
        tool6: {
          name: "אזמל",
          explanation:
            "האיזמל הוא חלק ממשפחת הכלים למקצוענים בלבד, והוא משמש לחציבה ולפיסול של אבנים.",
          questions: [
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `טעות`,
              ans2: `טעות`,
              ans3: `נכון`,
              ans4: `טעות`,
              correctAns: `ans3`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `טעות`,
              ans2: `נכון`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans2`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `טעות`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `נכון`,
              correctAns: `ans4`,
            },
          ],
        },
        tool7: {
          name: "קאטר",
          explanation:
            "הקאטר נחשב חלק ממשפחת הכלים לפירוק פצצות ויכול לשמש לחיתוך כבלי החשמל שמפעילים את הפצצה.",
          questions: [
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `טעות`,
              ans2: `טעות`,
              ans3: `נכון`,
              ans4: `טעות`,
              correctAns: `ans3`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
            {
              type: `multiple`,
              question: `בלה בלה`,
              ans1: `נכון`,
              ans2: `טעות`,
              ans3: `טעות`,
              ans4: `טעות`,
              correctAns: `ans1`,
            },
          ],
        },
      },
    },
  },
};
