// Needs minimum 18 questions

const DATA = {
  // multiple and binary questions
  "בהד-6": {
    "קורס-1": {
      tools: {
        amountOfQuestions: 3,
        questions: [
          {
            type: `multiple`,
            question: ` מה התגובה שמקבלים כשמחשמלים מים?`,
            ans1: `נכון`,
            ans2: `טעות`,
            ans3: `טעות`,
            ans4: `טעות`,
            correctAns: `ans1`,
          },
          {
            type: `multiple`,
            question: `איך קוראים לי?`,
            ans1: `שיר`,
            ans2: `נגה`,
            ans3: `תמר`,
            ans4: `אלון`,
            correctAns: `ans3`,
          },
          {
            type: `multiple`,
            question: `בת כמה אני?`,
            ans1: `16`,
            ans2: `19`,
            ans3: `22`,
            ans4: `80`,
            correctAns: `ans2`,
          },
          {
            type: `binary`,
            question: `תלחצו על נכון`,
            correctAns: `true`,
          },
          {
            type: `multiple`,
            question: `מה משמעות הביטוי "בית לאומי לעם היהודי בארץ ישראל" שנמצא בהצהרת בלפור ובאיזו שנה הבריטים חתמו על הצהרת בלפור ולמה היהודים בארץ שנאו אותם?`,
            ans1: `טעות`,
            ans2: `טעות`,
            ans3: `נכון`,
            ans4: `טעות`,
            correctAns: `ans3`,
          },
          {
            type: `multiple`,
            question: `ציינו שלוש דרכים שבהן הניה מטונימית לטבע והסבירו את החשיבות של חוסר הסיפוק של הניה במהלך ילדותה בכפר וכיצד הוא מתקשר לחייה הבוגרים בעיר הגדולה ולרצונם של הפועלים שלא יודע שובע. בכתיבתכם הכניסו ציטוטים מהיצירה`,
            ans1: `טעות`,
            ans2: `נכון`,
            ans3: `טעות`,
            ans4: `טעות`,
            correctAns: `ans2`,
          },
          {
            type: `multiple`,
            question: `בלה בלה`,
            ans1: `טעות`,
            ans2: `טעות`,
            ans3: `טעות`,
            ans4: `נכון`,
            correctAns: `ans4`,
          },
          {
            type: `multiple`,
            question: `בלה בלה`,
            ans1: `נכון`,
            ans2: `טעות`,
            ans3: `טעות`,
            ans4: `טעות`,
            correctAns: `ans1`,
          },
          {
            type: `multiple`,
            question: `בלה בלה`,
            ans1: `טעות`,
            ans2: `טעות`,
            ans3: `נכון`,
            ans4: `טעות`,
            correctAns: `ans3`,
          },
          {
            type: `multiple`,
            question: `בלה בלה`,
            ans1: `טעות`,
            ans2: `נכון`,
            ans3: `טעות`,
            ans4: `טעות`,
            correctAns: `ans2`,
          },
          {
            type: `multiple`,
            question: `בלה בלה`,
            ans1: `נכון`,
            ans2: `טעות`,
            ans3: `טעות`,
            ans4: `טעות`,
            correctAns: `ans1`,
          },
          {
            type: `multiple`,
            question: `בלה בלה`,
            ans1: `נכון`,
            ans2: `טעות`,
            ans3: `טעות`,
            ans4: `טעות`,
            correctAns: `ans1`,
          },
          {
            type: `multiple`,
            question: `בלה בלה`,
            ans1: `נכון`,
            ans2: `טעות`,
            ans3: `טעות`,
            ans4: `טעות`,
            correctAns: `ans1`,
          },
          {
            type: `multiple`,
            question: `בלה בלה`,
            ans1: `נכון`,
            ans2: `טעות`,
            ans3: `טעות`,
            ans4: `טעות`,
            correctAns: `ans1`,
          },
          {
            type: `multiple`,
            question: `בלה בלה`,
            ans1: `נכון`,
            ans2: `טעות`,
            ans3: `טעות`,
            ans4: `טעות`,
            correctAns: `ans1`,
          },
          {
            type: `multiple`,
            question: `בלה בלה`,
            ans1: `נכון`,
            ans2: `טעות`,
            ans3: `טעות`,
            ans4: `טעות`,
            correctAns: `ans1`,
          },
          {
            type: `multiple`,
            question: `בלה בלה`,
            ans1: `נכון`,
            ans2: `טעות`,
            ans3: `טעות`,
            ans4: `טעות`,
            correctAns: `ans1`,
          },
          {
            type: `multiple`,
            question: `בלה בלה`,
            ans1: `נכון`,
            ans2: `טעות`,
            ans3: `טעות`,
            ans4: `טעות`,
            correctAns: `ans1`,
          },
          {
            type: `multiple`,
            question: `בלה בלה`,
            ans1: `נכון`,
            ans2: `טעות`,
            ans3: `טעות`,
            ans4: `טעות`,
            correctAns: `ans1`,
          },
          {
            type: `multiple`,
            question: `בלה בלה`,
            ans1: `נכון`,
            ans2: `טעות`,
            ans3: `טעות`,
            ans4: `טעות`,
            correctAns: `ans1`,
          },
          {
            type: `multiple`,
            question: `בלה בלה`,
            ans1: `נכון`,
            ans2: `טעות`,
            ans3: `טעות`,
            ans4: `טעות`,
            correctAns: `ans1`,
          },
          {
            type: `sixChoices`,
            question: `שאלה עם 6 בחירות`,
            ans1: `1תשובה`,
            ans2: `תשובה2`,
            ans3: `תשובה3`,
            ans4: `תשובה4`,
            ans5: `תשובה5`,
            ans6: `תשובה6`,
            correctAns: [`ans1`, `ans2`, `ans5`], // the legth will determine how many answers are reqwiered
          },
          {
            type: `multipleAllPic`,
            question: `שאלה אמריקאית שהתשובות שלה הן תמונות`,
            answers: [
              `./assets/media/panda.jpg`,
              `./assets/media/dog.jpg`,
              `./assets/media/panda.jpg`,
              `./assets/media/dog.jpg`,
            ], // the legth will determine how many pics will be im the question, one correct ans
            correctAns: `ans1`,
          },
          {
            type: `multipleAllPic`,
            question: `שאלה אמריקאית שהתשובות שלה הן תמונות`,
            answers: [
              `./assets/media/panda.jpg`,
              `./assets/media/dog.jpg`,
              `./assets/media/panda.jpg`,
              `./assets/media/dog.jpg`,
            ], // the legth will determine how many pics will be im the question, one correct ans
            correctAns: `ans1`,
          },
          {
            type: `multipleAllPic`,
            question: `שאלה אמריקאית שהתשובות שלה הן תמונות`,
            answers: [
              `./assets/media/panda.jpg`,
              `./assets/media/dog.jpg`,
              `./assets/media/panda.jpg`,
              `./assets/media/dog.jpg`,
            ], // the legth will determine how many pics will be im the question, one correct ans
            correctAns: `ans1`,
          },
          {
            type: `sixChoicesWithPic`,
            src: `./assets/media/panda.jpg`,
            question: `שאלה עם 6 בחירות ותמונה`,
            ans1: `1תשובה`,
            ans2: `תשובה2`,
            ans3: `תשובה3`,
            ans4: `תשובה4`,
            ans5: `תשובה5`,
            ans6: `תשובה6`,
            correctAns: [`ans1`, `ans2`, `ans5`],
          },
          {
            type: `multipleAllPic`,
            question: `שאלה אמריקאית שהתשובות שלה הן תמונות`,
            answers: [
              `./assets/media/panda.jpg`,
              `./assets/media/dog.jpg`,
              `./assets/media/panda.jpg`,
              `./assets/media/dog.jpg`,
            ], // the legth will determine how many pics will be im the question, one correct ans
            correctAns: `ans1`,
          },
          {
            type: `sixChoicesWithPic`,
            src: `./assets/media/panda.jpg`,
            question: `שאלה עם 6 בחירות ותמונה`,
            ans1: `1תשובה`,
            ans2: `תשובה2`,
            ans3: `תשובה3`,
            ans4: `תשובה4`,
            ans5: `תשובה5`,
            ans6: `תשובה6`,
            correctAns: [`ans1`, `ans2`, `ans5`],
          },
          {
            type: `multipleWithPic`,
            src: `./assets/media/panda.jpg`,
            question: `שאלה עם תמונה`,
            ans1: `1תשובה`,
            ans2: `תשובה2`,
            ans3: `תשובה3`,
            ans4: `תשובה4`,
            correctAns: `ans1`,
          },
          {
            type: `binary`,
            question: `סזבכבסססססססססססס`,
            correctAns: true,
          },
          {
            type: `binaryWithPic`,
            src: `./assets/media/dog.jpg`,
            question: `נכון או לא נכון עם תמונה`,
            correctAns: true,
          },
          {
            type: "completeSentence",
            sentence: [`חלק ראשון של המשפט`, `חלק שני של המשפט`], // put each part of the sentence as an string in the array
            dropDownAns: [`אופציה 1`, `אופציה 2`, `אופציה 3`, `אופציה 4`], // all the options that will apear in the dropDown.
            correctAns: "ans0", // location of answer in array
          },
        ],
        // sort to groups
        sortToGroups: {
          drop: [`קבוצה 1`, `קבוצה 2`, `קבוצה 3`],
          drag: [
            {
              drag: "קבוצה 1",
              group: 1,
            },
            {
              drag: "קבוצה 2",
              group: 2,
            },
            {
              drag: "קבוצה 3",
              group: 3,
            },
            {
              drag: "קבוצה 1",
              group: 1,
            },
            {
              drag: "קבוצה 2",
              group: 2,
            },
            {
              drag: "קבוצה 3",
              group: 3,
            },
            {
              drag: "קבוצה 1",
              group: 1,
            },
            {
              drag: "קבוצה 2",
              group: 2,
            },
            {
              drag: "קבוצה 3",
              group: 3,
            },
          ],
        },
      },
    },
  },
};

const COURSES = {
  'בה"ד-6': ["קורס-בהד-6", "קורס-2", "קורס-3", "קורס-4"],
  'בה"ד-7': ["קורס-בהד-7", "קורס-2", "קורס-3", "קורס-4"],
  'בה"ד-10': ["קורס-בהד-10", "קורס-2", "קורס-3", "קורס-4"],
  'בה"ד-11': ["קורס-1", "קורס-2", "קורס-3", "קורס-4"],
  'בה"ד-13': ["קורס-1", "קורס-2", "קורס-3", "קורס-4"],
  'בה"ד-20': ["קורס-1", "קורס-2", "קורס-3", "קורס-4"],
  'בה"ד-חינוך': ["קורס-1", "קורס-2", "קורס-3", "קורס-4"],
  מפקדה: ["קורס-1", "קורס-2", "קורס-3", "קורס-4"],
};
